export const myConfig ={
    des:'站点基本信息',
    footer:'数字文化传播北京市重点实验室-内部项目-做一个一丝不苟的人^_^',
    brand:'汉语智能写作项目',
    fetch_url:'http://10.3.129.185:3005/',
    pages:[
        {
            des:'高校工作总结',
            teamid:'1',
            1:[
            {
                des:'这个对象里保存了子页面的参数',
                title:'部门工作总结',
            },
            {
                des:'这个对象里保存了子页面的参数',                
                title:'个人工作总结',
            },
            ]
        },
        {
            des:'贺词',
            teamid:'2',
            1:[
            {
                des:'',
                title:'祝寿词',
            },
            {
                des:'',                
                title:'婚礼贺词',
            },
            ]
        },
        {
            des:'典礼致辞',
            teamid:'3',
            1:[
            {
                des:'',
                title:'开学典礼致辞',
            },
            {
                des:'',                
                title:'毕业典礼致辞',
            },
            ]
        },
        {
            des:'短文体',
            teamid:'4',
            1:[
            {
                des:'',
                title:'请假条',
            },
            {
                des:'',                
                title:'求职信',
            },
            ]
        },
        {
            des:'测试页面',
            teamid:'5',
        },
    ]};