export const myConfig ={
    des:'站点基本信息',
    footer:'数字文化传播北京市重点实验室-内部项目-做一个一丝不苟的人^_^',
    brand:'汉语智能写作项目',
    fetch_url:'http://139.129.58.131:3005/',
    pages:[
        {
            des:'教育公文智能写作',
            teamid:'1',
        },
        {
            des:'日用文书智能写作',
            teamid:'2',
        },
        {
            des:'测试页面',
            teamid:'3',
        },
    ]};